-- Generate Wards
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-1-G', 'General Ward', '1', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-1-I', 'ICU Ward', '1', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-1-E', 'Emergency Ward', '1', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-2-G', 'General Ward', '2', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-2-I', 'ICU Ward', '2', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-2-E', 'Emergency Ward', '2', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-3-G', 'General Ward', '3', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-3-I', 'ICU Ward', '3', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-3-E', 'Emergency Ward', '3', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-4-G', 'General Ward', '4', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-4-I', 'ICU Ward', '4', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-4-E', 'Emergency Ward', '4', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-5-G', 'General Ward', '5', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-5-I', 'ICU Ward', '5', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-5-E', 'Emergency Ward', '5', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-6-G', 'General Ward', '6', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-6-I', 'ICU Ward', '6', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-6-E', 'Emergency Ward', '6', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-7-G', 'General Ward', '7', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-7-I', 'ICU Ward', '7', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-7-E', 'Emergency Ward', '7', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-8-G', 'General Ward', '8', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-8-I', 'ICU Ward', '8', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-8-E', 'Emergency Ward', '8', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-9-G', 'General Ward', '9', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-9-I', 'ICU Ward', '9', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-9-E', 'Emergency Ward', '9', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-10-G', 'General Ward', '10', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-10-I', 'ICU Ward', '10', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-10-E', 'Emergency Ward', '10', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-11-G', 'General Ward', '11', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-11-I', 'ICU Ward', '11', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-11-E', 'Emergency Ward', '11', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-12-G', 'General Ward', '12', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-12-I', 'ICU Ward', '12', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-12-E', 'Emergency Ward', '12', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-13-G', 'General Ward', '13', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-13-I', 'ICU Ward', '13', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-13-E', 'Emergency Ward', '13', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-14-G', 'General Ward', '14', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-14-I', 'ICU Ward', '14', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-14-E', 'Emergency Ward', '14', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-15-G', 'General Ward', '15', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-15-I', 'ICU Ward', '15', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-15-E', 'Emergency Ward', '15', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-16-G', 'General Ward', '16', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-16-I', 'ICU Ward', '16', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-16-E', 'Emergency Ward', '16', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-17-G', 'General Ward', '17', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-17-I', 'ICU Ward', '17', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-17-E', 'Emergency Ward', '17', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-18-G', 'General Ward', '18', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-18-I', 'ICU Ward', '18', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-18-E', 'Emergency Ward', '18', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-19-G', 'General Ward', '19', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-19-I', 'ICU Ward', '19', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-19-E', 'Emergency Ward', '19', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-20-G', 'General Ward', '20', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-20-I', 'ICU Ward', '20', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-20-E', 'Emergency Ward', '20', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-21-G', 'General Ward', '21', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-21-I', 'ICU Ward', '21', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-21-E', 'Emergency Ward', '21', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-22-G', 'General Ward', '22', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-22-I', 'ICU Ward', '22', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-22-E', 'Emergency Ward', '22', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-23-G', 'General Ward', '23', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-23-I', 'ICU Ward', '23', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-23-E', 'Emergency Ward', '23', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-24-G', 'General Ward', '24', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-24-I', 'ICU Ward', '24', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-24-E', 'Emergency Ward', '24', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-25-G', 'General Ward', '25', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-25-I', 'ICU Ward', '25', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-25-E', 'Emergency Ward', '25', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-26-G', 'General Ward', '26', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-26-I', 'ICU Ward', '26', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-26-E', 'Emergency Ward', '26', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-27-G', 'General Ward', '27', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-27-I', 'ICU Ward', '27', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-27-E', 'Emergency Ward', '27', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-28-G', 'General Ward', '28', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-28-I', 'ICU Ward', '28', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-28-E', 'Emergency Ward', '28', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-29-G', 'General Ward', '29', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-29-I', 'ICU Ward', '29', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-29-E', 'Emergency Ward', '29', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-30-G', 'General Ward', '30', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-30-I', 'ICU Ward', '30', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-30-E', 'Emergency Ward', '30', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-31-G', 'General Ward', '31', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-31-I', 'ICU Ward', '31', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-31-E', 'Emergency Ward', '31', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-32-G', 'General Ward', '32', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-32-I', 'ICU Ward', '32', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-32-E', 'Emergency Ward', '32', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-33-G', 'General Ward', '33', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-33-I', 'ICU Ward', '33', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-33-E', 'Emergency Ward', '33', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-34-G', 'General Ward', '34', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-34-I', 'ICU Ward', '34', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-34-E', 'Emergency Ward', '34', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-35-G', 'General Ward', '35', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-35-I', 'ICU Ward', '35', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-35-E', 'Emergency Ward', '35', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-36-G', 'General Ward', '36', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-36-I', 'ICU Ward', '36', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-36-E', 'Emergency Ward', '36', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-37-G', 'General Ward', '37', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-37-I', 'ICU Ward', '37', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-37-E', 'Emergency Ward', '37', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-38-G', 'General Ward', '38', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-38-I', 'ICU Ward', '38', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-38-E', 'Emergency Ward', '38', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-39-G', 'General Ward', '39', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-39-I', 'ICU Ward', '39', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-39-E', 'Emergency Ward', '39', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-40-G', 'General Ward', '40', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-40-I', 'ICU Ward', '40', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-40-E', 'Emergency Ward', '40', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-41-G', 'General Ward', '41', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-41-I', 'ICU Ward', '41', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-41-E', 'Emergency Ward', '41', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-42-G', 'General Ward', '42', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-42-I', 'ICU Ward', '42', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-42-E', 'Emergency Ward', '42', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-43-G', 'General Ward', '43', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-43-I', 'ICU Ward', '43', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-43-E', 'Emergency Ward', '43', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-44-G', 'General Ward', '44', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-44-I', 'ICU Ward', '44', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-44-E', 'Emergency Ward', '44', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-45-G', 'General Ward', '45', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-45-I', 'ICU Ward', '45', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-45-E', 'Emergency Ward', '45', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-46-G', 'General Ward', '46', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-46-I', 'ICU Ward', '46', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-46-E', 'Emergency Ward', '46', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-47-G', 'General Ward', '47', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-47-I', 'ICU Ward', '47', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-47-E', 'Emergency Ward', '47', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-48-G', 'General Ward', '48', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-48-I', 'ICU Ward', '48', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-48-E', 'Emergency Ward', '48', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-49-G', 'General Ward', '49', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-49-I', 'ICU Ward', '49', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-49-E', 'Emergency Ward', '49', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-50-G', 'General Ward', '50', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-50-I', 'ICU Ward', '50', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-50-E', 'Emergency Ward', '50', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-51-G', 'General Ward', '51', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-51-I', 'ICU Ward', '51', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-51-E', 'Emergency Ward', '51', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-52-G', 'General Ward', '52', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-52-I', 'ICU Ward', '52', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-52-E', 'Emergency Ward', '52', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-53-G', 'General Ward', '53', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-53-I', 'ICU Ward', '53', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-53-E', 'Emergency Ward', '53', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-54-G', 'General Ward', '54', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-54-I', 'ICU Ward', '54', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-54-E', 'Emergency Ward', '54', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-55-G', 'General Ward', '55', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-55-I', 'ICU Ward', '55', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-55-E', 'Emergency Ward', '55', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-56-G', 'General Ward', '56', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-56-I', 'ICU Ward', '56', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-56-E', 'Emergency Ward', '56', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-57-G', 'General Ward', '57', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-57-I', 'ICU Ward', '57', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-57-E', 'Emergency Ward', '57', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-58-G', 'General Ward', '58', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-58-I', 'ICU Ward', '58', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-58-E', 'Emergency Ward', '58', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-59-G', 'General Ward', '59', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-59-I', 'ICU Ward', '59', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-59-E', 'Emergency Ward', '59', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-60-G', 'General Ward', '60', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-60-I', 'ICU Ward', '60', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-60-E', 'Emergency Ward', '60', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-61-G', 'General Ward', '61', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-61-I', 'ICU Ward', '61', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-61-E', 'Emergency Ward', '61', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-62-G', 'General Ward', '62', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-62-I', 'ICU Ward', '62', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-62-E', 'Emergency Ward', '62', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-63-G', 'General Ward', '63', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-63-I', 'ICU Ward', '63', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-63-E', 'Emergency Ward', '63', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-64-G', 'General Ward', '64', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-64-I', 'ICU Ward', '64', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-64-E', 'Emergency Ward', '64', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-65-G', 'General Ward', '65', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-65-I', 'ICU Ward', '65', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-65-E', 'Emergency Ward', '65', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-66-G', 'General Ward', '66', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-66-I', 'ICU Ward', '66', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-66-E', 'Emergency Ward', '66', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-67-G', 'General Ward', '67', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-67-I', 'ICU Ward', '67', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-67-E', 'Emergency Ward', '67', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-68-G', 'General Ward', '68', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-68-I', 'ICU Ward', '68', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-68-E', 'Emergency Ward', '68', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-69-G', 'General Ward', '69', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-69-I', 'ICU Ward', '69', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-69-E', 'Emergency Ward', '69', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-70-G', 'General Ward', '70', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-70-I', 'ICU Ward', '70', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-70-E', 'Emergency Ward', '70', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-71-G', 'General Ward', '71', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-71-I', 'ICU Ward', '71', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-71-E', 'Emergency Ward', '71', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-72-G', 'General Ward', '72', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-72-I', 'ICU Ward', '72', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-72-E', 'Emergency Ward', '72', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-73-G', 'General Ward', '73', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-73-I', 'ICU Ward', '73', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-73-E', 'Emergency Ward', '73', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-74-G', 'General Ward', '74', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-74-I', 'ICU Ward', '74', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-74-E', 'Emergency Ward', '74', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-75-G', 'General Ward', '75', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-75-I', 'ICU Ward', '75', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-75-E', 'Emergency Ward', '75', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-76-G', 'General Ward', '76', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-76-I', 'ICU Ward', '76', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-76-E', 'Emergency Ward', '76', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-77-G', 'General Ward', '77', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-77-I', 'ICU Ward', '77', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-77-E', 'Emergency Ward', '77', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-78-G', 'General Ward', '78', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-78-I', 'ICU Ward', '78', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-78-E', 'Emergency Ward', '78', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-79-G', 'General Ward', '79', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-79-I', 'ICU Ward', '79', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-79-E', 'Emergency Ward', '79', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-80-G', 'General Ward', '80', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-80-I', 'ICU Ward', '80', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-80-E', 'Emergency Ward', '80', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-81-G', 'General Ward', '81', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-81-I', 'ICU Ward', '81', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-81-E', 'Emergency Ward', '81', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-82-G', 'General Ward', '82', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-82-I', 'ICU Ward', '82', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-82-E', 'Emergency Ward', '82', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-83-G', 'General Ward', '83', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-83-I', 'ICU Ward', '83', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-83-E', 'Emergency Ward', '83', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-84-G', 'General Ward', '84', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-84-I', 'ICU Ward', '84', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-84-E', 'Emergency Ward', '84', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-85-G', 'General Ward', '85', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-85-I', 'ICU Ward', '85', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-85-E', 'Emergency Ward', '85', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-86-G', 'General Ward', '86', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-86-I', 'ICU Ward', '86', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-86-E', 'Emergency Ward', '86', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-87-G', 'General Ward', '87', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-87-I', 'ICU Ward', '87', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-87-E', 'Emergency Ward', '87', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-88-G', 'General Ward', '88', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-88-I', 'ICU Ward', '88', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-88-E', 'Emergency Ward', '88', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-89-G', 'General Ward', '89', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-89-I', 'ICU Ward', '89', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-89-E', 'Emergency Ward', '89', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-90-G', 'General Ward', '90', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-90-I', 'ICU Ward', '90', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-90-E', 'Emergency Ward', '90', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-91-G', 'General Ward', '91', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-91-I', 'ICU Ward', '91', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-91-E', 'Emergency Ward', '91', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-92-G', 'General Ward', '92', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-92-I', 'ICU Ward', '92', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-92-E', 'Emergency Ward', '92', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-93-G', 'General Ward', '93', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-93-I', 'ICU Ward', '93', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-93-E', 'Emergency Ward', '93', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-94-G', 'General Ward', '94', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-94-I', 'ICU Ward', '94', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-94-E', 'Emergency Ward', '94', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-95-G', 'General Ward', '95', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-95-I', 'ICU Ward', '95', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-95-E', 'Emergency Ward', '95', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-96-G', 'General Ward', '96', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-96-I', 'ICU Ward', '96', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-96-E', 'Emergency Ward', '96', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-97-G', 'General Ward', '97', 10, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-97-I', 'ICU Ward', '97', 5, 0);
INSERT INTO wards (id, name, hospital_id, total, occupied) VALUES ('W-97-E', 'Emergency Ward', '97', 5, 0);

-- Generate Beds
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G1', 'General', 'Occupied', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G2', 'General', 'Occupied', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G3', 'General', 'Available', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G4', 'General', 'Available', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G5', 'General', 'Available', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G6', 'General', 'Available', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G7', 'General', 'Occupied', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G8', 'General', 'Occupied', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G9', 'General', 'Occupied', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-G10', 'General', 'Available', 'W-1-G', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-I1', 'ICU', 'Available', 'W-1-I', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-I2', 'ICU', 'Available', 'W-1-I', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-I3', 'ICU', 'Available', 'W-1-I', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-I4', 'ICU', 'Occupied', 'W-1-I', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-I5', 'ICU', 'Occupied', 'W-1-I', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-E1', 'Emergency', 'Occupied', 'W-1-E', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-E2', 'Emergency', 'Available', 'W-1-E', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-E3', 'Emergency', 'Available', 'W-1-E', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-E4', 'Emergency', 'Available', 'W-1-E', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-1-E5', 'Emergency', 'Occupied', 'W-1-E', '1');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G1', 'General', 'Occupied', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G2', 'General', 'Occupied', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G3', 'General', 'Available', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G4', 'General', 'Available', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G5', 'General', 'Occupied', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G6', 'General', 'Available', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G7', 'General', 'Available', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G8', 'General', 'Occupied', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G9', 'General', 'Available', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-G10', 'General', 'Occupied', 'W-2-G', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-I1', 'ICU', 'Available', 'W-2-I', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-I2', 'ICU', 'Occupied', 'W-2-I', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-I3', 'ICU', 'Occupied', 'W-2-I', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-I4', 'ICU', 'Available', 'W-2-I', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-I5', 'ICU', 'Available', 'W-2-I', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-E1', 'Emergency', 'Available', 'W-2-E', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-E2', 'Emergency', 'Occupied', 'W-2-E', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-E3', 'Emergency', 'Occupied', 'W-2-E', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-E4', 'Emergency', 'Available', 'W-2-E', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-2-E5', 'Emergency', 'Occupied', 'W-2-E', '2');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G1', 'General', 'Available', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G2', 'General', 'Available', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G3', 'General', 'Available', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G4', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G5', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G6', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G7', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G8', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G9', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-G10', 'General', 'Occupied', 'W-3-G', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-I1', 'ICU', 'Available', 'W-3-I', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-I2', 'ICU', 'Available', 'W-3-I', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-I3', 'ICU', 'Available', 'W-3-I', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-I4', 'ICU', 'Available', 'W-3-I', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-I5', 'ICU', 'Available', 'W-3-I', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-E1', 'Emergency', 'Occupied', 'W-3-E', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-E2', 'Emergency', 'Available', 'W-3-E', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-E3', 'Emergency', 'Occupied', 'W-3-E', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-E4', 'Emergency', 'Occupied', 'W-3-E', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-3-E5', 'Emergency', 'Occupied', 'W-3-E', '3');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G1', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G2', 'General', 'Occupied', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G3', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G4', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G5', 'General', 'Occupied', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G6', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G7', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G8', 'General', 'Available', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G9', 'General', 'Occupied', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-G10', 'General', 'Occupied', 'W-4-G', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-I1', 'ICU', 'Available', 'W-4-I', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-I2', 'ICU', 'Occupied', 'W-4-I', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-I3', 'ICU', 'Available', 'W-4-I', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-I4', 'ICU', 'Occupied', 'W-4-I', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-I5', 'ICU', 'Available', 'W-4-I', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-E1', 'Emergency', 'Available', 'W-4-E', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-E2', 'Emergency', 'Available', 'W-4-E', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-E3', 'Emergency', 'Occupied', 'W-4-E', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-E4', 'Emergency', 'Available', 'W-4-E', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-4-E5', 'Emergency', 'Occupied', 'W-4-E', '4');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G1', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G2', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G3', 'General', 'Occupied', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G4', 'General', 'Occupied', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G5', 'General', 'Occupied', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G6', 'General', 'Occupied', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G7', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G8', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G9', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-G10', 'General', 'Available', 'W-5-G', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-I1', 'ICU', 'Available', 'W-5-I', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-I2', 'ICU', 'Occupied', 'W-5-I', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-I3', 'ICU', 'Occupied', 'W-5-I', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-I4', 'ICU', 'Available', 'W-5-I', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-I5', 'ICU', 'Available', 'W-5-I', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-E1', 'Emergency', 'Available', 'W-5-E', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-E2', 'Emergency', 'Occupied', 'W-5-E', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-E3', 'Emergency', 'Available', 'W-5-E', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-E4', 'Emergency', 'Occupied', 'W-5-E', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-5-E5', 'Emergency', 'Occupied', 'W-5-E', '5');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G1', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G2', 'General', 'Available', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G3', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G4', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G5', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G6', 'General', 'Available', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G7', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G8', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G9', 'General', 'Occupied', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-G10', 'General', 'Available', 'W-6-G', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-I1', 'ICU', 'Occupied', 'W-6-I', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-I2', 'ICU', 'Available', 'W-6-I', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-I3', 'ICU', 'Occupied', 'W-6-I', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-I4', 'ICU', 'Occupied', 'W-6-I', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-I5', 'ICU', 'Occupied', 'W-6-I', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-E1', 'Emergency', 'Available', 'W-6-E', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-E2', 'Emergency', 'Occupied', 'W-6-E', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-E3', 'Emergency', 'Occupied', 'W-6-E', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-E4', 'Emergency', 'Occupied', 'W-6-E', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-6-E5', 'Emergency', 'Available', 'W-6-E', '6');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G1', 'General', 'Available', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G2', 'General', 'Available', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G3', 'General', 'Available', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G4', 'General', 'Occupied', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G5', 'General', 'Occupied', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G6', 'General', 'Occupied', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G7', 'General', 'Available', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G8', 'General', 'Occupied', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G9', 'General', 'Occupied', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-G10', 'General', 'Available', 'W-7-G', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-I1', 'ICU', 'Available', 'W-7-I', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-I2', 'ICU', 'Available', 'W-7-I', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-I3', 'ICU', 'Occupied', 'W-7-I', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-I4', 'ICU', 'Occupied', 'W-7-I', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-I5', 'ICU', 'Occupied', 'W-7-I', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-E1', 'Emergency', 'Occupied', 'W-7-E', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-E2', 'Emergency', 'Occupied', 'W-7-E', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-E3', 'Emergency', 'Occupied', 'W-7-E', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-E4', 'Emergency', 'Available', 'W-7-E', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-7-E5', 'Emergency', 'Available', 'W-7-E', '7');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G1', 'General', 'Occupied', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G2', 'General', 'Occupied', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G3', 'General', 'Occupied', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G4', 'General', 'Occupied', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G5', 'General', 'Available', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G6', 'General', 'Available', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G7', 'General', 'Available', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G8', 'General', 'Available', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G9', 'General', 'Occupied', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-G10', 'General', 'Available', 'W-8-G', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-I1', 'ICU', 'Available', 'W-8-I', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-I2', 'ICU', 'Available', 'W-8-I', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-I3', 'ICU', 'Available', 'W-8-I', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-I4', 'ICU', 'Available', 'W-8-I', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-I5', 'ICU', 'Occupied', 'W-8-I', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-E1', 'Emergency', 'Occupied', 'W-8-E', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-E2', 'Emergency', 'Available', 'W-8-E', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-E3', 'Emergency', 'Occupied', 'W-8-E', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-E4', 'Emergency', 'Available', 'W-8-E', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-8-E5', 'Emergency', 'Available', 'W-8-E', '8');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G1', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G2', 'General', 'Occupied', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G3', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G4', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G5', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G6', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G7', 'General', 'Occupied', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G8', 'General', 'Available', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G9', 'General', 'Occupied', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-G10', 'General', 'Occupied', 'W-9-G', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-I1', 'ICU', 'Occupied', 'W-9-I', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-I2', 'ICU', 'Available', 'W-9-I', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-I3', 'ICU', 'Occupied', 'W-9-I', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-I4', 'ICU', 'Occupied', 'W-9-I', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-I5', 'ICU', 'Available', 'W-9-I', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-E1', 'Emergency', 'Occupied', 'W-9-E', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-E2', 'Emergency', 'Occupied', 'W-9-E', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-E3', 'Emergency', 'Available', 'W-9-E', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-E4', 'Emergency', 'Available', 'W-9-E', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-9-E5', 'Emergency', 'Occupied', 'W-9-E', '9');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G1', 'General', 'Available', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G2', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G3', 'General', 'Available', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G4', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G5', 'General', 'Available', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G6', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G7', 'General', 'Available', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G8', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G9', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-G10', 'General', 'Occupied', 'W-10-G', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-I1', 'ICU', 'Occupied', 'W-10-I', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-I2', 'ICU', 'Available', 'W-10-I', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-I3', 'ICU', 'Occupied', 'W-10-I', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-I4', 'ICU', 'Available', 'W-10-I', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-I5', 'ICU', 'Occupied', 'W-10-I', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-E1', 'Emergency', 'Available', 'W-10-E', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-E2', 'Emergency', 'Available', 'W-10-E', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-E3', 'Emergency', 'Occupied', 'W-10-E', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-E4', 'Emergency', 'Occupied', 'W-10-E', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-10-E5', 'Emergency', 'Occupied', 'W-10-E', '10');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G1', 'General', 'Occupied', 'W-11-G', '11');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G2', 'General', 'Available', 'W-11-G', '11');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G3', 'General', 'Available', 'W-11-G', '11');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G4', 'General', 'Occupied', 'W-11-G', '11');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G5', 'General', 'Available', 'W-11-G', '11');
INSERT INTO beds (id, type, status, ward_id, hospital_id) VALUES ('B-11-G6', 'General', 'Available', 'W-11-G', '11');
